FROM python:3.12

ENV PYTHONUNBUFFERED 1

RUN \
   apt-get -y update  && apt-get -y upgrade && apt-get -y dist-upgrade 

RUN apt-get update

WORKDIR /code/epin_website

COPY requirements.txt /code/epin_website/

RUN \
    pip install --upgrade pip setuptools wheel \
    && pip install --upgrade pip \
    && pip install --upgrade pip setuptools wheel \
    && pip install -r requirements.txt

COPY . ./epin_website


CMD ["celery", "-A", "epin_website.celery", "worker", "--loglevel=INFO"]